# Screen dimensions
BOARD_WIDTH = 800
HEIGHT = 800
ANALYSIS_WIDTH = 420
FULL_WIDTH = 800+ANALYSIS_WIDTH
CENTER_SQUARES = {(3, 3), (3, 4), (4, 3), (4, 4)}

# Board dimensions
ROWS = 8
COLS = 8
SQSIZE = BOARD_WIDTH//COLS

